import Head from "next/head";
import MainLayout from "@/layout/MainLayout";
import Hero from "@/components/Hero";
import {
  fetchActivity,
  fetchBanners,
  fetchCategory,
  fetchPromo,
} from "../utils/api";
import Banner from "@/components/Banner";
import Category from "@/components/Category";
import Promo from "@/components/Promo";
import Activity from "@/components/Activity";

export async function getServerSideProps() {
  const dataBanners = await fetchBanners();
  const banners = dataBanners?.data;

  const dataCategory = await fetchCategory();
  const categories = dataCategory?.data;

  const dataPromo = await fetchPromo();
  const promos = dataPromo?.data;

  const dataActivity = await fetchActivity();
  const activities = dataActivity?.data;

  return { props: { banners, categories, promos, activities } };
}

export default function Home({ banners, categories, promos, activities }) {
  return (
    <>
      <Head>
        <title>TravelGo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <Hero />
        <Category categories={categories} />
        <Promo promos={promos} />
        <Banner banners={banners} />
        <Activity activities={activities} />
      </MainLayout>
    </>
  );
}
